/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RandomNumberGeneratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "entropyOracle"
      | "getRandomNumber"
      | "getTotalGenerated"
      | "hasRandomNumber"
      | "isGenerated"
      | "randomNumbers"
      | "requestRandomNumber"
      | "totalGenerated"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RandomNumberGenerated" | "RandomNumberRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalGenerated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRandomNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isGenerated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "randomNumbers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomNumber",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGenerated",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalGenerated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGenerated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGenerated",
    data: BytesLike
  ): Result;
}

export namespace RandomNumberGeneratedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requestNumber: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, requestNumber: bigint];
  export interface OutputObject {
    requestId: bigint;
    requestNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomNumberRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, tag: BytesLike];
  export type OutputTuple = [requestId: bigint, tag: string];
  export interface OutputObject {
    requestId: bigint;
    tag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RandomNumberGenerator extends BaseContract {
  connect(runner?: ContractRunner | null): RandomNumberGenerator;
  waitForDeployment(): Promise<this>;

  interface: RandomNumberGeneratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getRandomNumber: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "view"
  >;

  getTotalGenerated: TypedContractMethod<[], [bigint], "view">;

  hasRandomNumber: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  isGenerated: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  randomNumbers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  requestRandomNumber: TypedContractMethod<
    [tag: BytesLike],
    [bigint],
    "payable"
  >;

  totalGenerated: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRandomNumber"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalGenerated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRandomNumber"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isGenerated"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "randomNumbers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "requestRandomNumber"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "totalGenerated"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "RandomNumberGenerated"
  ): TypedContractEvent<
    RandomNumberGeneratedEvent.InputTuple,
    RandomNumberGeneratedEvent.OutputTuple,
    RandomNumberGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RandomNumberRequested"
  ): TypedContractEvent<
    RandomNumberRequestedEvent.InputTuple,
    RandomNumberRequestedEvent.OutputTuple,
    RandomNumberRequestedEvent.OutputObject
  >;

  filters: {
    "RandomNumberGenerated(uint256,uint256)": TypedContractEvent<
      RandomNumberGeneratedEvent.InputTuple,
      RandomNumberGeneratedEvent.OutputTuple,
      RandomNumberGeneratedEvent.OutputObject
    >;
    RandomNumberGenerated: TypedContractEvent<
      RandomNumberGeneratedEvent.InputTuple,
      RandomNumberGeneratedEvent.OutputTuple,
      RandomNumberGeneratedEvent.OutputObject
    >;

    "RandomNumberRequested(uint256,bytes32)": TypedContractEvent<
      RandomNumberRequestedEvent.InputTuple,
      RandomNumberRequestedEvent.OutputTuple,
      RandomNumberRequestedEvent.OutputObject
    >;
    RandomNumberRequested: TypedContractEvent<
      RandomNumberRequestedEvent.InputTuple,
      RandomNumberRequestedEvent.OutputTuple,
      RandomNumberRequestedEvent.OutputObject
    >;
  };
}
